# Generated by Django 5.2.7 on 2025-10-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_city_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='seats',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='package',
            name='seats_remaining',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
